remote_theme: analytics-link/analytics-link.github.io
url: "https://vidhyav656.github.io" # the subpath of your site, e.g. /blog
baseurl: "theme-demo" # the base hostname & protocol for your site, e.g. http://example.com
